### ISSUE TITLE
Create Kanban Board

### ISSUE THREAD

**Issue by Santiago220991** [Santiago220991/Recipe-App#10]
All tasks should have time estimates and your job is to distribute them between team members in a fair way.
The common tasks will be divided among all of you or completed as a team (pair programming).
All tasks should be based on the cards from your Kanban board.

Link to the project: https://github.com/Santiago220991/Recipe-App/projects/1

This is a group of two members:

- Fernando Salas.
- Santiago Cárdenas.

**Comment by sja-thedude** [comment]
## Invalid Code Review Request ❌

Hi @Santiago220991 & @LuisSalas94, This is @sja-thedude your code reviewer.

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

You have submitted a project, that doesn't have a link to the Github kanban board. Kindly make sure to add it.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by Santiago220991** [comment]
Thanks. I will add the link to the project right now. :+1:

**Comment by brytebee** [comment]
Hi, @ 👋,

Good job so far coming so far with the progress you've made! 💪💪

## Highlights
You have done amazing in the following:
- Team number provided.✔️
- Link provide.✔️
- Cards are assigned to team members fairly.✔️
 
However, there are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/VL48WGMDjD64umCEkv/giphy.gif)

# Required Changes ♻️
- The link should open to the Kanban board and not the repository.
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Please, remember to tag me in your question so I can receive the notification.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brytebee in your question so I can receive the notification.
### _**Use @brytebee on slack for faster responses.**_


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Santiago220991** [comment]
Hi, @brytebee I'm going to change the link. However, the update of the README.md file is not a requirement in this pull request we are going to update it later. Thanks. :+1:

**Comment by DammyShittu** [comment]
Hi @Santiago220991 @LuisSalas94,

## APPROVED 🟢

## Highlights
✔️ Descriptive PR
✔️ Passing linters
✔️ Good branch name

Great implementation of all the requirements in this milestone. 👏 

_You have done an amazing job 👍_

Your project is complete!  There is nothing else to say other than... it's time to merge it. :shipit: 

Congratulations! 🎉 

## CHEERS AND HAPPY CODING!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
